version: "3"

includes:
  ci:
    dir: .
    taskfile: "./taskfiles/ci.taskfile.yml"

tasks:
  # build
  build:
    cmds:
      - ./gradlew --parallel build
      - mkdir -p ./deployment/build
      - cp ./build/libs/Craftan-*-all.jar ./deployment/build/craftan.jar

  # code
  format:
    cmds:
      - ./gradlew ktlintFormat

  # docker
  docker:build:
    cmds:
      - >
        docker build
        --file ./deployment/Dockerfile
        --tag craftan-local:latest
        .
  docker-compose:up:
    cmds:
      - task: build
      - >
        docker compose
        --file ./deployment/docker-compose.yml
        up
        --build
        --detach
  docker-compose:down:
    cmds:
      - >
        docker compose
        --file ./deployment/docker-compose.yml
        down
        --remove-orphans
