version: "3.9"

volumes:
  craftan-server:

services:
  paper-server:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "5005:5005"
    volumes:
      - craftan-server:/app
