---
name: "Build Process"

on:
  push:
  workflow_dispatch:

jobs:
  compilation:
    name: "application compilation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout project code"
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - name: "check code compilation"
        run: "task ci:code:build"
        shell: "bash"
    timeout-minutes: 5

  docker:
    name: "docker build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout project code"
        uses: actions/checkout@v4
      - name: "setup qemu"
        uses: docker/setup-qemu-action@v3
      - name: "setup docker buildx"
        uses: docker/setup-buildx-action@v3
      - name: "build image"
        uses: docker/build-push-action@v6
        with:
          context: "."
          file: "./deployment/Dockerfile"
          platforms: "linux/amd64"
          push: "false"
          tags: "craftan/craftan:${{ github.ref_name}}"
    timeout-minutes: 5
